# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20160330_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
