# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20160330_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
